### ISSUE TITLE
index NormalizedDebt

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-influx#12]
### Acceptance criteria
- index `outstandingDebt` as basis for weighting of FICO score (as aggregator function in outflux (see ticket #10)
    - get `interestRatePerSecond` from `API.query.loans.activeLoan()`
    - get `normalisedDebt` from `API.query.loans.activeLoan()`
    - use the interest rate to fetch the `accumulatedRate` from `API.query.interestAccrual.rates()`
    - index `outstandingDebt` by multiplying `normalisedDebt` x `accumulatedRate`
    - periodically reindex and calculate `outstandingDebt` for all active loans

**Comment by filo87** [comment]
Outstanding debt cannot be indexed currently: see https://github.com/embrio-tech/centrifuge-subql/issues/146

Indexing Normalized Debt instead
