### ISSUE TITLE
index maturity for t-bill pools

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-influx#20]
## User story
As (who?) a borrower/issuer
I want (what?) to have an overview of the different maturities of the treasury bills in my pool 
So that (why?) the maturities can be visualised with the Pod Indexer and I know when to pay back my assets on time, give the investor an overview how my assets are going

## Acceptance criteria
Fetching the data of the different terms of the assets (treasury bills)  

Example pool: https://app-dev.k-f.dev/issuer/442507375/assets

**Comment by filo87** [comment]
@annamehr Can you help us refine that :P ?

**Comment by annamehr** [comment]
@filo87 I added some colour to the issue, let me know if you need more information :)

**Comment by filo87** [comment]
Depends on embrio-tech/centrifuge-subql#150

**Comment by annamehr** [comment]
Data fields from the pod: 

* Security type
* Par value
* Issue date
* Coupon
* Term 
* Maturity date

**Comment by offerijns** [comment]
I think we should index the maturity date from chain (https://github.com/centrifuge/centrifuge-chain/blob/a3bd197dc146419ea9eddd72390632f227d8c7b6/pallets/loans/src/types/mod.rs#L99, you can ignore the extension date for now), and then store this as two separate properties:
- The actual maturity as unix timestamp
- The time difference from now to maturity (maybe this can be derived when querying? not sure).

The latter can then be used to display something like the weighted debt by maturity ("X% of the pool is maturing in the next 3 0days", ...). It should be stored/derived as a signed integer, so it can also be used to report on overdue assets / deliquencies ("X amount is overdue by 30-60 days", ...).

**Comment by filo87** [comment]
Implemented
