### ISSUE TITLE
index additional loan KPIs from chain

### ISSUE THREAD

**Issue by filo87** [embrio-tech/centrifuge-influx#29]
### User story

> **As** as a aggregation designer
**I want** additional data to be indexed from chain
**So that** i can offer better statistics

- Outstanding debt
   - now defined as Outstanding principal + Outstanding interest
- Present value
- Actual maturity date
- (Time from now to maturity)
- Actual origination date
- Written off %
- Total borrowed amount
- Total repaid amount separated in principal, interest and unscheduled

### Acceptance criteria

- [x] Data above snapshot regularly and usable in aggregation pipelines

https://github.com/embrio-tech/centrifuge-influx/issues/20#issuecomment-1636795628

**Comment by filo87** [comment]
@offerijns in the last meeting we discussed we need to include more data about loans and index it from chain.... 

Can you help me here to refine what exactly the data is...and where to find it?

**Comment by offerijns** [comment]
Attempted runtime API integration in Centrifuge App: https://github.com/centrifuge/apps/pull/1528/commits/4cd7e17698cd666aa24d010f07801feebcd850b4

**Comment by offerijns** [comment]
Centrifuge Chain implementation of the portfolio runtime API: https://github.com/centrifuge/centrifuge-chain/blob/24e19b60b8fff3fdf2ac2c798bb8813839c90893/pallets/loans/src/lib.rs#L971

Exact type that is returned per loan: https://github.com/centrifuge/centrifuge-chain/blob/main/pallets/loans/src/entities/loans.rs#L499

**Comment by filo87** [comment]
@onnovisser @offerijns 

> Attempted runtime API integration in Centrifuge App: https://github.com/centrifuge/apps/commit/4cd7e17698cd666aa24d010f07801feebcd850b4

Is there a branch in centrifuge-apps that I can use with this code? especially with the RuntimeCall decorations?
